### PR TITLE
Loginprofileanalytics

### PR DESCRIPTION
**Pull request by iKAN2025**
maybe I can manually commit this for schema?

### CODE REVIEW

**Comment by iKAN2025** [comment]
Nikhil changed it for duplicate email, but you can change it back. The setsections is code I’m working on but I’ll probably push it to Mort’s after we’re done integrating. You can uncomment it.

**Comment by iKAN2025** [comment]
@aaguy-hue thanks!

**Comment by iKAN2025** [comment]
You can keep mortensen’s div too! :)

**Comment by aaguy-hue** [comment]
@iKAN2025 this looks great, thank you so much! There was some error with some `SectionDTO` class when I uncommented setSections, so I left it commented out for now. This looks good and I will merge this pull request, but when you have made the following changes, make another pull request.
1. Finish setSections()
2. Make the changes requested here: https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/36#issuecomment-2495183449

**Pull request merged**
